// <auto-generated />
using System;
using AtoGobMx.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtoGobMx.Migrations
{
    [DbContext(typeof(AtoGobMxContext))]
    [Migration("20221201213448_correccion_vales2")]
    partial class correccion_vales2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AtoGobMx.Models.Alumbrado", b =>
                {
                    b.Property<int>("AlumbradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DescripcionDomicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EstatusId")
                        .HasColumnType("int");

                    b.Property<int?>("InventarioAlumbradoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreObra")
                        .HasColumnType("longtext");

                    b.Property<int?>("TareaTipoId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneExpediente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AlumbradoId");

                    b.HasIndex("EstatusId");

                    b.HasIndex("InventarioAlumbradoId");

                    b.HasIndex("TareaTipoId");

                    b.ToTable("Alumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.Archivos", b =>
                {
                    b.Property<int>("ArchivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ExpedienteDigitalId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoArchivo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ArchivoId");

                    b.HasIndex("ExpedienteDigitalId");

                    b.ToTable("Archivos");
                });

            modelBuilder.Entity("AtoGobMx.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Area");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            Archivado = false,
                            DepartamentoId = 1,
                            Nombre = "Soporte TI"
                        });
                });

            modelBuilder.Entity("AtoGobMx.Models.Aseo", b =>
                {
                    b.Property<int>("AseoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstablecimientoPublico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AseoId");

                    b.ToTable("Aseo");
                });

            modelBuilder.Entity("AtoGobMx.Models.Cementerios", b =>
                {
                    b.Property<int>("CementeriosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DireccionId")
                        .HasColumnType("int");

                    b.Property<int>("EspaciosDisponibles")
                        .HasColumnType("int");

                    b.Property<float>("Latitud")
                        .HasColumnType("float");

                    b.Property<float>("Longitud")
                        .HasColumnType("float");

                    b.Property<float>("MetrosCorrespondientes")
                        .HasColumnType("float");

                    b.Property<string>("NombrePropietario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroEspasios")
                        .HasColumnType("int");

                    b.HasKey("CementeriosId");

                    b.HasIndex("DireccionId");

                    b.ToTable("Cementerios");
                });

            modelBuilder.Entity("AtoGobMx.Models.Departamentos", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DepartamentoId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            DepartamentoId = 1,
                            Archivado = false,
                            Nombre = "Direccion de Sistemas"
                        });
                });

            modelBuilder.Entity("AtoGobMx.Models.DireccionCementerio", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCementerio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroExterior")
                        .HasColumnType("int");

                    b.HasKey("DireccionId");

                    b.ToTable("DireccionCementerio");
                });

            modelBuilder.Entity("AtoGobMx.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("PuestoTrabajoId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneExpediente")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("PuestoTrabajoId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            EmpleadoId = 1,
                            Archivado = false,
                            AreaId = 1,
                            DepartamentoId = 1,
                            FechaAlta = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            NombreCompleto = "Administrador",
                            PuestoTrabajoId = 1,
                            TieneExpediente = true
                        });
                });

            modelBuilder.Entity("AtoGobMx.Models.EmpleadosAlumbrado", b =>
                {
                    b.Property<int>("AlumbradoEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteAlumbradoId")
                        .HasColumnType("int");

                    b.HasKey("AlumbradoEmpleadoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ExpedienteAlumbradoId");

                    b.ToTable("EmpleadosAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.EstatusAlumbrado", b =>
                {
                    b.Property<int>("EstatusAlumbradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreEstatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EstatusAlumbradoId");

                    b.ToTable("EstatusAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.ExpedienteAlumbrado", b =>
                {
                    b.Property<int>("ExpedienteAlumbradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AlumbradoId")
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("DescripcionSolucion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Localidad")
                        .HasColumnType("longtext");

                    b.Property<string>("LugarPublico")
                        .HasColumnType("longtext");

                    b.Property<string>("Nomenclatura")
                        .HasColumnType("longtext");

                    b.Property<int?>("PAT_VehiculoVehiculoId")
                        .HasColumnType("int");

                    b.HasKey("ExpedienteAlumbradoId");

                    b.HasIndex("AlumbradoId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("PAT_VehiculoVehiculoId");

                    b.ToTable("ExpedienteAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.ExpedienteDigital", b =>
                {
                    b.Property<int>("ExpedienteDigitalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Calle")
                        .HasColumnType("longtext");

                    b.Property<int?>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("longtext");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Localidad")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumeroExterior")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroInterior")
                        .HasColumnType("int");

                    b.HasKey("ExpedienteDigitalId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ExpedienteDigital");

                    b.HasData(
                        new
                        {
                            ExpedienteDigitalId = 1,
                            Archivado = false,
                            EmpleadoId = 1
                        });
                });

            modelBuilder.Entity("AtoGobMx.Models.InventarioAlumbrado", b =>
                {
                    b.Property<int>("InventarioAlumbradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("InventarioAlumbradoId");

                    b.ToTable("InventarioAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.OP_Empleados", b =>
                {
                    b.Property<int>("EmpleadoObrasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("ObraId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoObrasId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ObraId");

                    b.ToTable("OP_Empleados");
                });

            modelBuilder.Entity("AtoGobMx.Models.OP_EstatusObras", b =>
                {
                    b.Property<int>("EstatusObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EstatusObraId");

                    b.ToTable("OP_EstatusObras");
                });

            modelBuilder.Entity("AtoGobMx.Models.OP_Obras", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EstatusObraId")
                        .HasColumnType("int");

                    b.Property<float>("Latitud")
                        .HasColumnType("float");

                    b.Property<float>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ObraId");

                    b.HasIndex("EstatusObraId");

                    b.ToTable("ObrasPublicas");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Armeria", b =>
                {
                    b.Property<int>("ArmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Calibre")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nomenclatura")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoArma")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ArmaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Armeria");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_EquipoComputo", b =>
                {
                    b.Property<int>("EquipoComputoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Almacenamiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInventario")
                        .HasColumnType("longtext");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("EstatusEquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MemoriaRAM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Procesador")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EquipoComputoId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("EstatusEquipoId");

                    b.ToTable("EquipoComputo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_EstatusEquipo", b =>
                {
                    b.Property<int>("EstatusEquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EstatusEquipoId");

                    b.ToTable("InventarioEstatus");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_EstatusVehiculo", b =>
                {
                    b.Property<int>("EstatusVehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EstatusVehiculoId");

                    b.ToTable("EstatusVehiculo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Mobiliario", b =>
                {
                    b.Property<int>("MobiliarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoMobiliarioId")
                        .HasColumnType("int");

                    b.HasKey("MobiliarioId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("TipoMobiliarioId");

                    b.ToTable("Mobiliario");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Monitor", b =>
                {
                    b.Property<int>("MonitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EquipoComputoId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<int?>("Pulgadas")
                        .HasColumnType("int");

                    b.HasKey("MonitorId");

                    b.HasIndex("EquipoComputoId");

                    b.ToTable("Monitor");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Mouse", b =>
                {
                    b.Property<int>("MouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EquipoComputoId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoConexion")
                        .HasColumnType("longtext");

                    b.HasKey("MouseId");

                    b.HasIndex("EquipoComputoId");

                    b.ToTable("Mouse");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Teclado", b =>
                {
                    b.Property<int>("TecladoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EquipoComputoId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoConexion")
                        .HasColumnType("longtext");

                    b.HasKey("TecladoId");

                    b.HasIndex("EquipoComputoId");

                    b.ToTable("Teclado");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_TipoMobiliario", b =>
                {
                    b.Property<int>("TipoMobiliarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TipoMobiliarioId");

                    b.ToTable("TipoMobiliario");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("AñoLanzamiento")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EstatusVehiculoId")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Puertas")
                        .HasColumnType("int");

                    b.Property<string>("Transmisión")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VehiculoId");

                    b.HasIndex("EstatusVehiculoId");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_ControlVales", b =>
                {
                    b.Property<int>("ControlValeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("EstatusValeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaEmicion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaVigencia")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoId")
                        .HasColumnType("int");

                    b.HasKey("ControlValeId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("EstatusValeId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("TipoId");

                    b.ToTable("ControlDeVales");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_DetalleProducto", b =>
                {
                    b.Property<int>("DetalleProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DetalleValeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleProductoId");

                    b.HasIndex("DetalleValeId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PROV_DetalleProducto");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_DetalleVale", b =>
                {
                    b.Property<int>("DetalleValeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("ControlValeId")
                        .HasColumnType("int");

                    b.Property<float?>("IVA")
                        .HasColumnType("float");

                    b.Property<int?>("PROV_ProductoProductoId")
                        .HasColumnType("int");

                    b.Property<float?>("Precio")
                        .HasColumnType("float");

                    b.Property<float?>("Total")
                        .HasColumnType("float");

                    b.HasKey("DetalleValeId");

                    b.HasIndex("ControlValeId");

                    b.HasIndex("PROV_ProductoProductoId");

                    b.ToTable("PROV_DetalleVale");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_EstatusVale", b =>
                {
                    b.Property<int>("EstatusValeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EstatusValeId");

                    b.ToTable("PROV_EstatusVale");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductoId");

                    b.ToTable("PROV_Producto");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RepresentanteLegal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Telefono")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("ProveedorId");

                    b.ToTable("PROV_Proveedor");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_TipoVales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TipoId");

                    b.ToTable("TipoVales");
                });

            modelBuilder.Entity("AtoGobMx.Models.PuestoTrabajo", b =>
                {
                    b.Property<int>("PuestoTrabajoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("PuestoTrabajoId");

                    b.HasIndex("AreaId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("PuestoTrabajo");

                    b.HasData(
                        new
                        {
                            PuestoTrabajoId = 1,
                            Archivado = false,
                            AreaId = 1,
                            DepartamentoId = 1,
                            Nombre = "Auxiliar de soporte"
                        });
                });

            modelBuilder.Entity("AtoGobMx.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Archivado = false,
                            Nombre = "Administrador"
                        });
                });

            modelBuilder.Entity("AtoGobMx.Models.Ruta", b =>
                {
                    b.Property<int>("RutaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Obsevacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RutaId");

                    b.ToTable("Ruta");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_Cita", b =>
                {
                    b.Property<int>("CitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("FechaDesde")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FechaHasta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CitaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Cita");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_ExpedienteMedico", b =>
                {
                    b.Property<int>("ExpedienteMedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alergias")
                        .HasColumnType("longtext");

                    b.Property<string>("AntecedentesFamiliares")
                        .HasColumnType("longtext");

                    b.Property<string>("AntecedentesPersonales")
                        .HasColumnType("longtext");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Discapacidad")
                        .HasColumnType("longtext");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<float?>("Estatura")
                        .HasColumnType("float");

                    b.Property<float?>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSangre")
                        .HasColumnType("longtext");

                    b.HasKey("ExpedienteMedicoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ExpedienteMedico");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaMedicamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProductoId");

                    b.ToTable("Medicamento");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_ProductosReceta", b =>
                {
                    b.Property<int>("ProductoRecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("RecetaId")
                        .HasColumnType("int");

                    b.Property<int?>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("ProductoRecetaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RecetaId");

                    b.ToTable("ProductoReceta");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_Receta", b =>
                {
                    b.Property<int>("RecetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("diagnostico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecetaId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Receta");
                });

            modelBuilder.Entity("AtoGobMx.Models.TareaTipoAlumbrado", b =>
                {
                    b.Property<int>("TareaTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("NombreTarea")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TareaTipoId");

                    b.ToTable("TareaTipoAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConfirmarContraseña")
                        .HasColumnType("longtext");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("RoleId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Archivado = false,
                            ConfirmarContraseña = "Admin123",
                            Contraseña = "Admin123",
                            EmpleadoId = 1,
                            NombreUsuario = "Administrador",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("AtoGobMx.Models.VehiculosAlumbrado", b =>
                {
                    b.Property<int>("VehiculoAlumbradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("EstatusVehiculoId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteAlumbradoId")
                        .HasColumnType("int");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("VehiculoAlumbradoId");

                    b.HasIndex("EstatusVehiculoId");

                    b.HasIndex("ExpedienteAlumbradoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("VehiculosAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.Zona", b =>
                {
                    b.Property<int>("zonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archivado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("zonaId");

                    b.ToTable("Zona");
                });

            modelBuilder.Entity("AtoGobMx.Models.Alumbrado", b =>
                {
                    b.HasOne("AtoGobMx.Models.EstatusAlumbrado", "Estatus")
                        .WithMany("Alumbrado")
                        .HasForeignKey("EstatusId");

                    b.HasOne("AtoGobMx.Models.InventarioAlumbrado", "InventarioAlumbrado")
                        .WithMany("Alumbrado")
                        .HasForeignKey("InventarioAlumbradoId");

                    b.HasOne("AtoGobMx.Models.TareaTipoAlumbrado", "TareaTipoAlumbrado")
                        .WithMany("Alumbrado")
                        .HasForeignKey("TareaTipoId");

                    b.Navigation("Estatus");

                    b.Navigation("InventarioAlumbrado");

                    b.Navigation("TareaTipoAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.Archivos", b =>
                {
                    b.HasOne("AtoGobMx.Models.ExpedienteDigital", "expedienteDigital")
                        .WithMany("Archivos")
                        .HasForeignKey("ExpedienteDigitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("expedienteDigital");
                });

            modelBuilder.Entity("AtoGobMx.Models.Area", b =>
                {
                    b.HasOne("AtoGobMx.Models.Departamentos", "Departamentos")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("AtoGobMx.Models.Cementerios", b =>
                {
                    b.HasOne("AtoGobMx.Models.DireccionCementerio", "DireccionCementerio")
                        .WithMany("Cementerios")
                        .HasForeignKey("DireccionId");

                    b.Navigation("DireccionCementerio");
                });

            modelBuilder.Entity("AtoGobMx.Models.Empleado", b =>
                {
                    b.HasOne("AtoGobMx.Models.Area", "Area")
                        .WithMany("Empleados")
                        .HasForeignKey("AreaId");

                    b.HasOne("AtoGobMx.Models.Departamentos", "Departamentos")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("AtoGobMx.Models.PuestoTrabajo", "PuestoTrabajo")
                        .WithMany()
                        .HasForeignKey("PuestoTrabajoId");

                    b.Navigation("Area");

                    b.Navigation("Departamentos");

                    b.Navigation("PuestoTrabajo");
                });

            modelBuilder.Entity("AtoGobMx.Models.EmpleadosAlumbrado", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleados")
                        .WithMany("EmpleadosAlumbrado")
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("AtoGobMx.Models.ExpedienteAlumbrado", "ExpedienteAlumbrado")
                        .WithMany("EmpleadosAlumbrado")
                        .HasForeignKey("ExpedienteAlumbradoId");

                    b.Navigation("Empleados");

                    b.Navigation("ExpedienteAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.ExpedienteAlumbrado", b =>
                {
                    b.HasOne("AtoGobMx.Models.Alumbrado", "Alumbrado")
                        .WithMany("ExpedienteAlumbrado")
                        .HasForeignKey("AlumbradoId");

                    b.HasOne("AtoGobMx.Models.Area", "Area")
                        .WithMany("ExpedienteAlumbrado")
                        .HasForeignKey("AreaId");

                    b.HasOne("AtoGobMx.Models.Departamentos", "Departamentos")
                        .WithMany("ExpedienteAlumbrado")
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("AtoGobMx.Models.PAT_Vehiculo", null)
                        .WithMany("ExpedienteAlumbrado")
                        .HasForeignKey("PAT_VehiculoVehiculoId");

                    b.Navigation("Alumbrado");

                    b.Navigation("Area");

                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("AtoGobMx.Models.ExpedienteDigital", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AtoGobMx.Models.OP_Empleados", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("AtoGobMx.Models.OP_Obras", "ObrasPublicas")
                        .WithMany("OP_Empleados")
                        .HasForeignKey("ObraId");

                    b.Navigation("Empleados");

                    b.Navigation("ObrasPublicas");
                });

            modelBuilder.Entity("AtoGobMx.Models.OP_Obras", b =>
                {
                    b.HasOne("AtoGobMx.Models.OP_EstatusObras", "OP_EstatusObras")
                        .WithMany("ObrasPublicas")
                        .HasForeignKey("EstatusObraId");

                    b.Navigation("OP_EstatusObras");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Armeria", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleado")
                        .WithMany("Armería")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_EquipoComputo", b =>
                {
                    b.HasOne("AtoGobMx.Models.Area", "Area")
                        .WithMany("EquiposComputo")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoGobMx.Models.Departamentos", "Departamentos")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoGobMx.Models.PAT_EstatusEquipo", "EstatusEquipo")
                        .WithMany("EquipoComputo")
                        .HasForeignKey("EstatusEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Departamentos");

                    b.Navigation("EstatusEquipo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Mobiliario", b =>
                {
                    b.HasOne("AtoGobMx.Models.Area", "Area")
                        .WithMany("Mobiliario")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoGobMx.Models.Departamentos", "Departamentos")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoGobMx.Models.PAT_TipoMobiliario", "TipoMobiliario")
                        .WithMany()
                        .HasForeignKey("TipoMobiliarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Departamentos");

                    b.Navigation("TipoMobiliario");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Monitor", b =>
                {
                    b.HasOne("AtoGobMx.Models.PAT_EquipoComputo", "EquipoComputo")
                        .WithMany()
                        .HasForeignKey("EquipoComputoId");

                    b.Navigation("EquipoComputo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Mouse", b =>
                {
                    b.HasOne("AtoGobMx.Models.PAT_EquipoComputo", "EquipoComputo")
                        .WithMany()
                        .HasForeignKey("EquipoComputoId");

                    b.Navigation("EquipoComputo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Teclado", b =>
                {
                    b.HasOne("AtoGobMx.Models.PAT_EquipoComputo", "EquipoComputo")
                        .WithMany()
                        .HasForeignKey("EquipoComputoId");

                    b.Navigation("EquipoComputo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Vehiculo", b =>
                {
                    b.HasOne("AtoGobMx.Models.PAT_EstatusVehiculo", "EstatusVehiculo")
                        .WithMany()
                        .HasForeignKey("EstatusVehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstatusVehiculo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_ControlVales", b =>
                {
                    b.HasOne("AtoGobMx.Models.Area", "Area")
                        .WithMany("ControlDeVales")
                        .HasForeignKey("AreaId");

                    b.HasOne("AtoGobMx.Models.Departamentos", "Departamentos")
                        .WithMany("ControlDeVales")
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("AtoGobMx.Models.Empleado", "Empleados")
                        .WithMany("ControlDeVales")
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("AtoGobMx.Models.PROV_EstatusVale", "PROV_EstatusVale")
                        .WithMany("ControlDeVales")
                        .HasForeignKey("EstatusValeId");

                    b.HasOne("AtoGobMx.Models.PROV_Proveedor", "PROV_Proveedor")
                        .WithMany("ControlDeVales")
                        .HasForeignKey("ProveedorId");

                    b.HasOne("AtoGobMx.Models.PROV_TipoVales", "TipoVales")
                        .WithMany("ControlDeVales")
                        .HasForeignKey("TipoId");

                    b.Navigation("Area");

                    b.Navigation("Departamentos");

                    b.Navigation("Empleados");

                    b.Navigation("PROV_EstatusVale");

                    b.Navigation("PROV_Proveedor");

                    b.Navigation("TipoVales");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_DetalleProducto", b =>
                {
                    b.HasOne("AtoGobMx.Models.PROV_DetalleVale", "PROV_DetalleVale")
                        .WithMany("PROV_DetalleProducto")
                        .HasForeignKey("DetalleValeId");

                    b.HasOne("AtoGobMx.Models.PROV_Producto", "PROV_Producto")
                        .WithMany("PROV_DetalleProducto")
                        .HasForeignKey("ProductoId");

                    b.Navigation("PROV_DetalleVale");

                    b.Navigation("PROV_Producto");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_DetalleVale", b =>
                {
                    b.HasOne("AtoGobMx.Models.PROV_ControlVales", "PROV_ControlVale")
                        .WithMany("PROV_DetalleVales")
                        .HasForeignKey("ControlValeId");

                    b.HasOne("AtoGobMx.Models.PROV_Producto", null)
                        .WithMany("PROV_DetalleVale")
                        .HasForeignKey("PROV_ProductoProductoId");

                    b.Navigation("PROV_ControlVale");
                });

            modelBuilder.Entity("AtoGobMx.Models.PuestoTrabajo", b =>
                {
                    b.HasOne("AtoGobMx.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("AtoGobMx.Models.Departamentos", "Departamentos")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.Navigation("Area");

                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_Cita", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_ExpedienteMedico", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleados")
                        .WithMany("ExpedienteMedico")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_ProductosReceta", b =>
                {
                    b.HasOne("AtoGobMx.Models.SERMED_Producto", "Producto")
                        .WithMany("ProductosReceta")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtoGobMx.Models.SERMED_Receta", "Receta")
                        .WithMany("ProductosReceta")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_Receta", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AtoGobMx.Models.Usuario", b =>
                {
                    b.HasOne("AtoGobMx.Models.Empleado", "Empleado")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("AtoGobMx.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId");

                    b.Navigation("Empleado");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AtoGobMx.Models.VehiculosAlumbrado", b =>
                {
                    b.HasOne("AtoGobMx.Models.PAT_EstatusVehiculo", "EstatusVehiculo")
                        .WithMany("VehiculosAlumbrado")
                        .HasForeignKey("EstatusVehiculoId");

                    b.HasOne("AtoGobMx.Models.ExpedienteAlumbrado", "ExpedienteAlumbrado")
                        .WithMany()
                        .HasForeignKey("ExpedienteAlumbradoId");

                    b.HasOne("AtoGobMx.Models.PAT_Vehiculo", "Vehiculo")
                        .WithMany("VehiculosAlumbrado")
                        .HasForeignKey("VehiculoId");

                    b.Navigation("EstatusVehiculo");

                    b.Navigation("ExpedienteAlumbrado");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("AtoGobMx.Models.Alumbrado", b =>
                {
                    b.Navigation("ExpedienteAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.Area", b =>
                {
                    b.Navigation("ControlDeVales");

                    b.Navigation("Empleados");

                    b.Navigation("EquiposComputo");

                    b.Navigation("ExpedienteAlumbrado");

                    b.Navigation("Mobiliario");
                });

            modelBuilder.Entity("AtoGobMx.Models.Departamentos", b =>
                {
                    b.Navigation("ControlDeVales");

                    b.Navigation("ExpedienteAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.DireccionCementerio", b =>
                {
                    b.Navigation("Cementerios");
                });

            modelBuilder.Entity("AtoGobMx.Models.Empleado", b =>
                {
                    b.Navigation("Armería");

                    b.Navigation("ControlDeVales");

                    b.Navigation("EmpleadosAlumbrado");

                    b.Navigation("ExpedienteMedico");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtoGobMx.Models.EstatusAlumbrado", b =>
                {
                    b.Navigation("Alumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.ExpedienteAlumbrado", b =>
                {
                    b.Navigation("EmpleadosAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.ExpedienteDigital", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("AtoGobMx.Models.InventarioAlumbrado", b =>
                {
                    b.Navigation("Alumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.OP_EstatusObras", b =>
                {
                    b.Navigation("ObrasPublicas");
                });

            modelBuilder.Entity("AtoGobMx.Models.OP_Obras", b =>
                {
                    b.Navigation("OP_Empleados");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_EstatusEquipo", b =>
                {
                    b.Navigation("EquipoComputo");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_EstatusVehiculo", b =>
                {
                    b.Navigation("VehiculosAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.PAT_Vehiculo", b =>
                {
                    b.Navigation("ExpedienteAlumbrado");

                    b.Navigation("VehiculosAlumbrado");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_ControlVales", b =>
                {
                    b.Navigation("PROV_DetalleVales");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_DetalleVale", b =>
                {
                    b.Navigation("PROV_DetalleProducto");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_EstatusVale", b =>
                {
                    b.Navigation("ControlDeVales");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_Producto", b =>
                {
                    b.Navigation("PROV_DetalleProducto");

                    b.Navigation("PROV_DetalleVale");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_Proveedor", b =>
                {
                    b.Navigation("ControlDeVales");
                });

            modelBuilder.Entity("AtoGobMx.Models.PROV_TipoVales", b =>
                {
                    b.Navigation("ControlDeVales");
                });

            modelBuilder.Entity("AtoGobMx.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_Producto", b =>
                {
                    b.Navigation("ProductosReceta");
                });

            modelBuilder.Entity("AtoGobMx.Models.SERMED_Receta", b =>
                {
                    b.Navigation("ProductosReceta");
                });

            modelBuilder.Entity("AtoGobMx.Models.TareaTipoAlumbrado", b =>
                {
                    b.Navigation("Alumbrado");
                });
#pragma warning restore 612, 618
        }
    }
}
